<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentLinksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentLinks = [
            [
                'id' => 2,
                'link_id' => 'LINK_HE9XETWP',
                'short_code' => 'VolOOfzz',
                'client_reference' => 'LOAN_2025_001',
                'client_id' => 3,
                'service_mapping_id' => null,
                'amount' => 75000.00,
                'currency' => 'TZS',
                'description' => 'Loan Repayment - Installment #3 of 12',
                'narration' => 'Monthly loan installment payment',
                'customer_phone' => '255723456789',
                'customer_name' => 'Sarah Johnson',
                'customer_email' => 'sarah.johnson@example.com',
                'payment_method' => 'mobile_money',
                'allowed_networks' => '["TZ-MPESA-C2B","TZ-AIRTEL-C2B","TZ-TIGO-C2B","TZ-HALOPESA-C2B"]',
                'allow_partial_payment' => null,
                'minimum_amount' => 75000.00,
                'maximum_amount' => 75000.00,
                'expires_at' => '2025-07-27 11:56:57',
                'max_uses' => 1,
                'current_uses' => 0,
                'status' => 'active',
                'is_reusable' => null,
                'is_public' => 1,
                'metadata' => '{"is_public_link":false,"customer_reference":"LOAN_2025_001","target_type":"individual","loan_id":"LOAN_2025_001","installment_number":3,"total_installments":12,"encrypted_data":{"data":"SF4vMRFOUcbSFAd4gusgwzizVT5GqlvpzadItrE5uYbs4uF1hgqwiCM+EMxZOvR2cgZ6bnlplUyUNiSQWCAEXS5wih8CowmoIP+3QrC0+D63N4r3vBU8ADbNRpRx6iVhwcfwMnf8Fv3hyfKZpDQ=","iv":"D4XzJ4oNhMiEbLgR","tag":"f6Dg+eA4y9NKsGJ2HknnXw=="},"security_hash":"8d5a980cabf0a0ac9fe674f44f84eede259a0c83a22d1551db17a6d910f64b0d","created_with_security":true,"security_version":"1.0"}',
                'settings' => null,
                'webhook_url' => null,
                'success_url' => 'https://example.com/success',
                'failure_url' => 'https://example.com/failure',
                'cancel_url' => null,
                'views_count' => 1,
                'last_viewed_at' => '2025-07-20 11:57:32',
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2025-07-20 11:56:57',
                'updated_at' => '2025-07-20 11:57:32',
            ],
            [
                'id' => 3,
                'link_id' => 'LINK_F2NETZY7',
                'short_code' => 'Y9KggxFx',
                'client_reference' => 'BUS_REG_2025_002',
                'client_id' => 3,
                'service_mapping_id' => null,
                'amount' => 150000.00,
                'currency' => 'TZS',
                'description' => 'Business Registration Fee',
                'narration' => 'Annual business registration renewal',
                'customer_phone' => '255689123456',
                'customer_name' => 'Michael Chen',
                'customer_email' => 'michael.chen@business.com',
                'payment_method' => 'mobile_money',
                'allowed_networks' => '["TZ-MPESA-C2B","TZ-AIRTEL-C2B","TZ-TIGO-C2B","TZ-HALOPESA-C2B"]',
                'allow_partial_payment' => null,
                'minimum_amount' => 150000.00,
                'maximum_amount' => 150000.00,
                'expires_at' => '2025-07-27 11:56:57',
                'max_uses' => 1,
                'current_uses' => 0,
                'status' => 'active',
                'is_reusable' => null,
                'is_public' => 1,
                'metadata' => '{"is_public_link":false,"customer_reference":"BUS_REG_2025_002","target_type":"individual","business_id":"BUS_2025_002","registration_type":"annual_renewal","encrypted_data":{"data":"iRge3yg+oQin20jQqs1kUJ39w/uiaID8gFgxfshJqbwCSQ3BAB4LuRuNcNYv++eBnmLb+cws3xM70anRzrOwT446HGcb88C2wFcOflWMsXNCdX/9BiaGk05d295Zs+VpArJZvT/0eYimxBGX1g==","iv":"2XgNrbvrLxbTUXKq","tag":"ptCRm3IIxk7xd537EOXfDw=="},"security_hash":"00870ebd87afaf93942045e7bf82dafdcbe129c879b333b41c577cf1a45aa8ae","created_with_security":true,"security_version":"1.0"}',
                'settings' => null,
                'webhook_url' => null,
                'success_url' => 'https://example.com/success',
                'failure_url' => 'https://example.com/failure',
                'cancel_url' => null,
                'views_count' => 0,
                'last_viewed_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2025-07-20 11:56:57',
                'updated_at' => '2025-07-20 11:56:57',
            ],
            [
                'id' => 4,
                'link_id' => 'LINK_GMNWKJTF',
                'short_code' => 'HG1GeJST',
                'client_reference' => 'INS_2025_003',
                'client_id' => 3,
                'service_mapping_id' => null,
                'amount' => 45000.00,
                'currency' => 'TZS',
                'description' => 'Insurance Premium Payment',
                'narration' => 'Quarterly health insurance premium',
                'customer_phone' => '255712345678',
                'customer_name' => 'Fatima Hassan',
                'customer_email' => 'fatima.hassan@example.com',
                'payment_method' => 'mobile_money',
                'allowed_networks' => '["TZ-MPESA-C2B","TZ-AIRTEL-C2B","TZ-TIGO-C2B","TZ-HALOPESA-C2B"]',
                'allow_partial_payment' => null,
                'minimum_amount' => 45000.00,
                'maximum_amount' => 45000.00,
                'expires_at' => '2025-07-27 11:56:57',
                'max_uses' => 1,
                'current_uses' => 0,
                'status' => 'active',
                'is_reusable' => null,
                'is_public' => 1,
                'metadata' => '{"is_public_link":false,"customer_reference":"INS_2025_003","target_type":"individual","insurance_id":"INS_2025_003","premium_type":"health","payment_frequency":"quarterly","encrypted_data":{"data":"4WIgcqE+HRXcRoNiObRyRAF9PbpqJ6I1Fbrkim15whCFsyLyLVM6bOQpugLSmUhk+h1xg3W+j7l8bhZemB7CYzfGjpJ5kYR/8ftlbcONSif0+qOUIHOmmShhn8trI9YzcC8bHQfDagc2HLJvptE=","iv":"m1Bs9tLItF1Svl4n","tag":"2y/CCiwHiG5vj4qjY9TuVg=="},"security_hash":"4df2e05ba6f71fc65840bbedb400910f6983664103fa329d13a55f019fd8ee2c","created_with_security":true,"security_version":"1.0"}',
                'settings' => null,
                'webhook_url' => null,
                'success_url' => 'https://example.com/success',
                'failure_url' => 'https://example.com/failure',
                'cancel_url' => null,
                'views_count' => 0,
                'last_viewed_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2025-07-20 11:56:57',
                'updated_at' => '2025-07-20 11:56:57',
            ],
            [
                'id' => 5,
                'link_id' => 'LINK_T14EQSRP',
                'short_code' => 'WDit087y',
                'client_reference' => 'CHURCH_SADAKA_001',
                'client_id' => 3,
                'service_mapping_id' => null,
                'amount' => 15000.00,
                'currency' => 'TZS',
                'description' => 'Sunday Service Donation - St. Mary\'s Church',
                'narration' => 'Weekly church donation for community development',
                'customer_phone' => null,
                'customer_name' => null,
                'customer_email' => null,
                'payment_method' => 'mobile_money',
                'allowed_networks' => '["TZ-MPESA-C2B","TZ-AIRTEL-C2B","TZ-TIGO-C2B","TZ-HALOPESA-C2B"]',
                'allow_partial_payment' => 1,
                'minimum_amount' => 5000.00,
                'maximum_amount' => 15000.00,
                'expires_at' => '2025-08-19 11:56:57',
                'max_uses' => 100,
                'current_uses' => 0,
                'status' => 'active',
                'is_reusable' => 1,
                'is_public' => 1,
                'metadata' => '{"is_public_link":true,"customer_reference":"CHURCH_SADAKA_001","target_type":"public","church_id":"ST_MARY_001","donation_type":"weekly_service","security_hash":"9a6d16cd0f70cb8907206287590c0be45ed59eca79f5a2235145b0fe89fc8334","created_with_security":true,"security_version":"1.0"}',
                'settings' => null,
                'webhook_url' => null,
                'success_url' => 'https://example.com/success',
                'failure_url' => 'https://example.com/failure',
                'cancel_url' => null,
                'views_count' => 1,
                'last_viewed_at' => '2025-07-20 11:57:40',
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2025-07-20 11:56:57',
                'updated_at' => '2025-07-20 11:57:40',
            ],
            [
                'id' => 6,
                'link_id' => 'LINK_R7IZWC6K',
                'short_code' => 'XWX1s6d1',
                'client_reference' => 'COMMUNITY_DEV_001',
                'client_id' => 3,
                'service_mapping_id' => null,
                'amount' => 25000.00,
                'currency' => 'TZS',
                'description' => 'Community Development Fund',
                'narration' => 'Contribution to local community development projects',
                'customer_phone' => null,
                'customer_name' => null,
                'customer_email' => null,
                'payment_method' => 'mobile_money',
                'allowed_networks' => '["TZ-MPESA-C2B","TZ-AIRTEL-C2B","TZ-TIGO-C2B","TZ-HALOPESA-C2B"]',
                'allow_partial_payment' => 1,
                'minimum_amount' => 10000.00,
                'maximum_amount' => 25000.00,
                'expires_at' => '2025-08-19 11:56:57',
                'max_uses' => 100,
                'current_uses' => 0,
                'status' => 'active',
                'is_reusable' => 1,
                'is_public' => 1,
                'metadata' => '{"is_public_link":true,"customer_reference":"COMMUNITY_DEV_001","target_type":"public","community_id":"LOCAL_COMM_001","project_type":"development","security_hash":"932f7b14ee9dce05dad76120250b515282e1e417f4bb123bc6ff01a82129698b","created_with_security":true,"security_version":"1.0"}',
                'settings' => null,
                'webhook_url' => null,
                'success_url' => 'https://example.com/success',
                'failure_url' => 'https://example.com/failure',
                'cancel_url' => null,
                'views_count' => 0,
                'last_viewed_at' => null,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => '2025-07-20 11:56:57',
                'updated_at' => '2025-07-20 11:56:57',
            ],
        ];

        // Clear existing data
        DB::table('payment_links')->truncate();

        // Insert new data
        foreach ($paymentLinks as $link) {
            DB::table('payment_links')->insert($link);
        }

        $this->command->info('Payment Links seeded successfully!');
    }
}
